from .interfaces import ICommand, INotifyPropertyChanged
from abc import ABCMeta
from pymagic9 import PropertyMeta
from typing import Any, Callable, List, NoReturn, Optional, overload, Set, Tuple, Type, Union

TypeINPC = Type[INotifyPropertyChanged]

__all__: List[str]

# def get_data_context() -> Optional[INotifyPropertyChanged]: ...
# def get_data_context_type_name() -> Optional[str]: ...

class BaseCommand(ICommand):
    __slots__: Tuple[str, ...]

    ce: Callable[..., bool]
    ce_kwargs: Optional[dict]
    ex: Callable[..., None]
    ex_kwargs: Optional[dict]

    def __init__(self,
                 execute: Callable[..., Any] = ...,
                 can_execute: Callable[..., bool] = ...,
                 ex_kwargs: Optional[dict] = ...,
                 ce_kwargs: Optional[dict] = ...) -> None: ...
    def can_execute(self, *args, **kwargs) -> Optional[bool]: ...
    def execute(self, *args, **kwargs) -> bool: ...

class CancelCommand(Exception):
    def __init__(self, msg: Optional[str] = ...) -> None: ...

class BaseNPC(INotifyPropertyChanged):
    __slots__: Tuple[str, ...]

    def NotifyPropertyChanged(self, propertyName: Optional[str]) -> None: ...
    def set(self, fieldName: str, value: Any, propertyName: Optional[str]) -> None: ...

class _BaseMMeta(type):
    def __call__(cls, *args, **kwargs) -> Union[type, NoReturn]: ...

class BaseM:  # TODO: use generics
    vm: INotifyPropertyChanged

    def __init__(self, vm: Optional[BaseVM] = ...) -> None: ...

class _ExposeMeta(PropertyMeta):
    def __call__(cls, *args, **kwargs) -> type: ...

class _BaseVMMeta(_ExposeMeta, ABCMeta): ...

class BaseVM(BaseNPC, metaclass=_BaseVMMeta):
    exposes: Tuple[str, ...]

class _DCMeta(type):
    __slots__: Tuple[str, ...]

    def __init__(cls, name, bases, attrs) -> None: ...
    def __call__(cls, *args, **kwargs) -> Optional[TypeINPC, NoReturn]: ...
    # def __getattr__(cls, item: Any) -> Optional[type, INotifyPropertyChanged, str, NoReturn]: ...
    # def __getattribute__(cls, item: Any) -> NoReturn: ...
    def __setattr__(cls, key: str, value: Any) -> NoReturn: ...

class DataContext(metaclass=_DCMeta):
    __slots__: Tuple[str, ...]

    cls: Optional[type]
    inst: Optional[TypeINPC]
    name: Optional[str]

    def __init__(self, cls: type) -> None: ...
    def __call__(self, *args: Any, **kwargs) -> TypeINPC: ...
    # def __getattr__(self, item: Any) -> Optional[type, INotifyPropertyChanged, str, NoReturn]: ...
    # def __getattribute__(self, item: Any) -> NoReturn: ...
    def __setattr__(self, key: str, value: Any) -> NoReturn: ...

_delay_exposure: Set[List[str]]

@overload
def exposer(*args: Any) -> NoReturn: ...
@overload
def exposer(func: Callable[..., Any]) -> Callable[..., Any]: ...
@overload
def exposer(prop: property) -> Optional[property, NoReturn]: ...
@overload
def exposer(cls: type, propName: str) -> None: ...
def _exposer(clsName: str, propName: str) -> None: ...
